-- المحسن ستور - قاعدة البيانات النهائية
-- انسخ هذا الملف بالكامل إلى Supabase > SQL Editor ثم اضغط Run

-- =========================
-- 1) Profiles
-- =========================
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  account_type text not null default 'buyer'
    check (account_type in ('buyer','seller','admin')),
  store_name text,
  address text,
  created_at timestamptz not null default now()
);

-- =========================
-- 2) Products
-- =========================
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric(12,2) not null default 0 check (price >= 0),
  category text,
  image_url text,
  icon text default '🛍️',
  stock integer not null default 0 check (stock >= 0),
  seller_id uuid references public.profiles(id) on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- لو جدول products موجود بالفعل، نتأكد أن الأعمدة المطلوبة موجودة
alter table public.products add column if not exists description text;
alter table public.products add column if not exists category text;
alter table public.products add column if not exists image_url text;
alter table public.products add column if not exists icon text default '🛍️';
alter table public.products add column if not exists stock integer default 0;
alter table public.products add column if not exists seller_id uuid references public.profiles(id) on delete set null;
alter table public.products add column if not exists is_active boolean default true;
alter table public.products add column if not exists created_at timestamptz default now();

-- تصحيح القيم القديمة
update public.products set is_active = true where is_active is null;
update public.products set stock = 0 where stock is null;

-- =========================
-- 3) Seller applications
-- =========================
create table if not exists public.seller_applications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  full_name text not null,
  email text not null,
  phone text not null,
  store_name text,
  address text,
  status text not null default 'pending'
    check (status in ('pending','approved','rejected')),
  admin_note text,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

-- =========================
-- 4) Helper: current profile
-- =========================
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and account_type = 'admin'
  );
$$;

create or replace function public.is_seller()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and account_type = 'seller'
  );
$$;

-- =========================
-- 5) Create profile automatically
-- =========================
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  wanted_type text;
begin
  wanted_type := coalesce(new.raw_user_meta_data->>'account_type', 'buyer');

  if wanted_type not in ('buyer','seller') then
    wanted_type := 'buyer';
  end if;

  insert into public.profiles (
    id, full_name, phone, account_type, store_name, address
  )
  values (
    new.id,
    nullif(new.raw_user_meta_data->>'full_name',''),
    nullif(new.raw_user_meta_data->>'phone',''),
    wanted_type,
    nullif(new.raw_user_meta_data->>'store_name',''),
    nullif(new.raw_user_meta_data->>'address','')
  )
  on conflict (id) do update set
    full_name = excluded.full_name,
    phone = excluded.phone,
    store_name = excluded.store_name,
    address = excluded.address;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- =========================
-- 6) RLS
-- =========================
alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.seller_applications enable row level security;

-- Profiles
drop policy if exists "profiles_select_own_or_admin" on public.profiles;
create policy "profiles_select_own_or_admin"
on public.profiles for select
to authenticated
using (id = auth.uid() or public.is_admin());

drop policy if exists "profiles_update_own_or_admin" on public.profiles;
create policy "profiles_update_own_or_admin"
on public.profiles for update
to authenticated
using (id = auth.uid() or public.is_admin())
with check (id = auth.uid() or public.is_admin());

-- Products: الجميع يشاهد المنتجات النشطة
drop policy if exists "products_select_active" on public.products;
create policy "products_select_active"
on public.products for select
to anon, authenticated
using (is_active = true or public.is_admin() or seller_id = auth.uid());

-- المدير والبائع الموافق عليه يستطيعان إضافة منتجات
drop policy if exists "products_insert_admin_or_seller" on public.products;
create policy "products_insert_admin_or_seller"
on public.products for insert
to authenticated
with check (
  public.is_admin()
  or (public.is_seller() and seller_id = auth.uid())
);

drop policy if exists "products_update_admin_or_owner" on public.products;
create policy "products_update_admin_or_owner"
on public.products for update
to authenticated
using (public.is_admin() or seller_id = auth.uid())
with check (public.is_admin() or seller_id = auth.uid());

drop policy if exists "products_delete_admin_or_owner" on public.products;
create policy "products_delete_admin_or_owner"
on public.products for delete
to authenticated
using (public.is_admin() or seller_id = auth.uid());

-- Seller applications
drop policy if exists "seller_applications_insert_own" on public.seller_applications;
create policy "seller_applications_insert_own"
on public.seller_applications for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "seller_applications_select_own_or_admin" on public.seller_applications;
create policy "seller_applications_select_own_or_admin"
on public.seller_applications for select
to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists "seller_applications_update_admin" on public.seller_applications;
create policy "seller_applications_update_admin"
on public.seller_applications for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- =========================
-- 7) Indexes
-- =========================
create index if not exists products_active_idx
on public.products (is_active);

create index if not exists products_seller_idx
on public.products (seller_id);

create index if not exists seller_applications_user_idx
on public.seller_applications (user_id);

create index if not exists seller_applications_status_idx
on public.seller_applications (status);

-- =========================
-- 8) جعل حسابك مديرًا
-- =========================
-- بعد إنشاء حسابك في الموقع، استبدل YOUR_USER_ID بالـ UUID الخاص بحسابك
-- ثم شغّل السطر التالي وحده:
--
-- update public.profiles
-- set account_type = 'admin'
-- where id = 'YOUR_USER_ID';
--
-- لا تضع البريد الإلكتروني أو كلمة المرور هنا؛ استخدم User ID فقط.

-- ===== إضافات المتجر المتعدد البائعين والطلبات =====
create table if not exists public.shipping_methods(id bigint generated by default as identity primary key,name text not null,price numeric(12,2) default 0,estimated_days text,is_active boolean default true);
insert into public.shipping_methods(name,price,estimated_days) values('أرامكس',80,'2-4 أيام'),('DHL',120,'1-3 أيام'),('بوسطة',60,'2-5 أيام') on conflict do nothing;
create table if not exists public.orders(id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,total_price numeric(12,2) not null default 0,status text not null default 'pending',shipping_address jsonb not null default '{}'::jsonb,payment_method text not null default 'cod',shipping_method_id bigint references public.shipping_methods(id),shipping_cost numeric(12,2) default 0,created_at timestamptz default now());
create table if not exists public.order_items(id bigint generated by default as identity primary key,order_id bigint not null references public.orders(id) on delete cascade,product_id bigint not null references public.products(id),quantity integer not null check(quantity>0),price numeric(12,2) not null);
create table if not exists public.cart_items(id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,product_id bigint not null references public.products(id) on delete cascade,quantity integer not null default 1 check(quantity>0),created_at timestamptz default now(),unique(user_id,product_id));
create table if not exists public.wishlist(id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,product_id bigint not null references public.products(id) on delete cascade,unique(user_id,product_id));
create table if not exists public.reviews(id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,product_id bigint not null references public.products(id) on delete cascade,rating integer not null check(rating between 1 and 5),comment text,created_at timestamptz default now(),unique(user_id,product_id));
create table if not exists public.addresses(id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,full_name text not null,phone text not null,city text not null,address text not null,created_at timestamptz default now());
alter table public.orders enable row level security; alter table public.order_items enable row level security; alter table public.cart_items enable row level security; alter table public.wishlist enable row level security; alter table public.reviews enable row level security; alter table public.addresses enable row level security; alter table public.shipping_methods enable row level security;
drop policy if exists shipping_public_read on public.shipping_methods; create policy shipping_public_read on public.shipping_methods for select using(is_active=true or public.is_admin());
drop policy if exists orders_owner_admin_read on public.orders; create policy orders_owner_admin_read on public.orders for select to authenticated using(user_id=auth.uid() or public.is_admin() or exists(select 1 from public.order_items oi join public.products p on p.id=oi.product_id where oi.order_id=orders.id and p.seller_id=auth.uid()));
drop policy if exists orders_owner_insert on public.orders; create policy orders_owner_insert on public.orders for insert to authenticated with check(user_id=auth.uid());
drop policy if exists orders_status_update on public.orders; create policy orders_status_update on public.orders for update to authenticated using(public.is_admin() or user_id=auth.uid() or exists(select 1 from public.order_items oi join public.products p on p.id=oi.product_id where oi.order_id=orders.id and p.seller_id=auth.uid())) with check(public.is_admin() or user_id=auth.uid() or exists(select 1 from public.order_items oi join public.products p on p.id=oi.product_id where oi.order_id=orders.id and p.seller_id=auth.uid()));
drop policy if exists order_items_read on public.order_items; create policy order_items_read on public.order_items for select to authenticated using(exists(select 1 from public.orders o where o.id=order_id and (o.user_id=auth.uid() or public.is_admin())) or exists(select 1 from public.products p where p.id=product_id and p.seller_id=auth.uid()));
drop policy if exists order_items_insert on public.order_items; create policy order_items_insert on public.order_items for insert to authenticated with check(exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid()));
drop policy if exists cart_owner_all on public.cart_items; create policy cart_owner_all on public.cart_items for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
drop policy if exists wish_owner_all on public.wishlist; create policy wish_owner_all on public.wishlist for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
drop policy if exists reviews_public_read on public.reviews; create policy reviews_public_read on public.reviews for select using(true);
drop policy if exists reviews_owner_insert on public.reviews; create policy reviews_owner_insert on public.reviews for insert to authenticated with check(user_id=auth.uid());
drop policy if exists addresses_owner_all on public.addresses; create policy addresses_owner_all on public.addresses for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
insert into storage.buckets(id,name,public) values('products','products',true) on conflict(id) do update set public=true;
drop policy if exists product_images_read on storage.objects; create policy product_images_read on storage.objects for select using(bucket_id='products');
drop policy if exists product_images_insert on storage.objects; create policy product_images_insert on storage.objects for insert to authenticated with check(bucket_id='products' and (public.is_admin() or public.is_seller()));
-- بعد إنشاء حسابك: update public.profiles set account_type='admin' where id='YOUR_USER_ID';

-- تحديث مهم: البائع الجديد يبقى Buyer حتى موافقة المدير، مع إنشاء طلب بائع تلقائيًا.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
declare wanted_type text;
begin
  wanted_type:=coalesce(new.raw_user_meta_data->>'account_type','buyer');
  if wanted_type not in ('buyer','seller') then wanted_type:='buyer'; end if;
  insert into public.profiles(id,full_name,phone,account_type,store_name,address)
  values(new.id,nullif(new.raw_user_meta_data->>'full_name',''),nullif(new.raw_user_meta_data->>'phone',''),case when wanted_type='seller' then 'buyer' else wanted_type end,nullif(new.raw_user_meta_data->>'store_name',''),nullif(new.raw_user_meta_data->>'address',''))
  on conflict(id) do update set full_name=excluded.full_name,phone=excluded.phone,store_name=excluded.store_name,address=excluded.address;
  if wanted_type='seller' then
    insert into public.seller_applications(user_id,full_name,email,phone,store_name,address)
    values(new.id,coalesce(nullif(new.raw_user_meta_data->>'full_name',''),'غير محدد'),new.email,coalesce(nullif(new.raw_user_meta_data->>'phone',''),'غير محدد'),nullif(new.raw_user_meta_data->>'store_name',''),nullif(new.raw_user_meta_data->>'address',''));
  end if;
  return new;
end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
